apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillcode-{{ .Values.metadata }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
  selector:
    app: frontend
