apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skillcode-{{ .Values.metadata  }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: skillcode-{{ .Values.metadata  }}
      labels:
        app: frontend
    spec: # pod spec
      containers:
      - name: frontend-container
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.imageTag }}"
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: BACKEND_URL
          value: {{ .Values.frontend.backendUrl | quote }}